name: Test Ansible Role

on: [push, pull_request]

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: run tox tests
        run: tox
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLE_DRIVER: 'docker'
